# Generated by Django 2.1.15 on 2020-12-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_text', models.CharField(max_length=200)),
                ('f_day', models.FloatField()),
                ('s_day', models.FloatField()),
                ('t_day', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
