# Generated by Django 2.1.15 on 2021-01-10 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.CharField(max_length=200)),
                ('price_close', models.FloatField()),
                ('f_day', models.FloatField()),
                ('s_day', models.FloatField()),
                ('t_day', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_text', models.CharField(max_length=200)),
                ('f_day', models.FloatField()),
                ('s_day', models.FloatField()),
                ('t_day', models.FloatField()),
                ('value', models.FloatField()),
                ('financetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stock_Type')),
            ],
        ),
        migrations.AddField(
            model_name='stock_prices',
            name='stocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stocks_List'),
        ),
    ]
