# Generated by Django 2.1.15 on 2020-12-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.CharField(max_length=200)),
                ('price_close', models.FloatField()),
                ('f_day', models.FloatField()),
                ('s_day', models.FloatField()),
                ('t_day', models.FloatField()),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stocks_List')),
            ],
        ),
    ]
