# Generated by Django 3.1.6 on 2021-03-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210123_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_text', models.CharField(max_length=200)),
                ('Asset_link', models.CharField(max_length=500)),
                ('f_day', models.FloatField(blank=True, null=True)),
                ('s_day', models.FloatField(blank=True, null=True)),
                ('t_day', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset_Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.CharField(max_length=200)),
                ('price_close', models.FloatField(blank=True, null=True)),
                ('f_day', models.FloatField(blank=True, null=True)),
                ('s_day', models.FloatField(blank=True, null=True)),
                ('t_day', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asset_list')),
            ],
        ),
        migrations.RemoveField(
            model_name='stocks_list',
            name='financetype',
        ),
        migrations.RenameModel(
            old_name='Stock_Type',
            new_name='Asset_Type',
        ),
        migrations.DeleteModel(
            name='Stock_Prices',
        ),
        migrations.DeleteModel(
            name='Stocks_List',
        ),
        migrations.AddField(
            model_name='asset_list',
            name='financetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asset_type'),
        ),
    ]
